
class Autogenerated {
  String? status;
  String? token;
  String? refreshToken;

  Autogenerated({this.status, this.token, this.refreshToken});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    token = json['token'];
    refreshToken = json['refreshToken'];
  }

}
